title: Oona Shigeno Risse-Adams
url: "https://oonashigenorisseadams.github.io"
baseurl: ""
description: "Personal blog of Oona Shigeno Risse-Adams"
permalink: pretty

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass
    sourcemap: never
nav:
 - name: "Outreach"
   link: "/outreach"
 - name: "Misc"
   link: "/misc"

favicon: true
favicon_location: "/favicon.ico"
favicon: true
favicon_location: "/favicon.ico"
