title: Oona Shigeno Risse-Adams
url: "https://oonashigenorisseadams.github.io"
baseurl: ""
description: "Personal blog of Oona Shigeno Risse-Adams"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

#footer: yes
#footer_url: "https://github.com/oonashigenorisseadams"
#footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Outreach"
   link: "/outreach"
 - name: "Misc"
   link: "/misc"

favicon: true
favicon_location: "/favicon.ico"
favicon: true
favicon_location: "/favicon.ico"
